jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # Any prerequisite steps
      - uses: actions/checkout@main

      # Deploy to local repo
      - name: Deploy
        uses: anilkumarthakur60/vuetify-portfolio@main
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build

      # Deploy to another repo
      - name: Deploy
        uses: anilkumarthakur60/vuetify-portfolio@main
        env:
          REPO: git@github.com:anilkumarthakur60/vuetify-portfolio.git

          BRANCH: gh-pages
          FOLDER: build
